### Create a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@test6.com",
    "password": "123456"
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@test1.com",
    "password": "123456"
}

### Get whoami
GET http://localhost:3000/auth/whoami

### Get user by id
GET http://localhost:3000/auth/getUserById/1

### Get user by email
GET http://localhost:3000/auth/getUserByEmail/test@test.com

### Update user
PATCH http://localhost:3000/auth/updateUser/1
Content-Type: application/json

{
    "name": "updated",
    "email": "test@test.com",
    "isActive": false
}

### Activate user
PATCH http://localhost:3000/auth/activateUser/1

### Delete user
DELETE http://localhost:3000/auth/deleteUser/1
